# Generated by Django 3.0.3 on 2020-02-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language_used',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
