# Generated by Django 3.0.3 on 2020-02-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_project_language_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='language',
        ),
    ]
