# Generated by Django 3.0.3 on 2020-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20200215_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_skills',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
